name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install vercel
        run: npm install -g vercel
      
      - name: Deploy vercel
        run: |
          vercel deploy public -n novelai-gallery --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
